import base64
import os
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import AsyncMock, patch

from sub2gen.core.database_runtime import DatabaseSettings
from sub2gen.core.postgres_database import coerce_boolean_parameters, translate_sql
from sub2gen.core.postgres_migrations import baseline_schema_signature, discover_migrations
from sub2gen.services.postgres_backup import (
    PostgresBackupError,
    create_postgres_archive,
    decrypt_archive,
    encrypt_archive,
    encrypted_archive_header,
    load_backup_keys,
)


class TestDatabaseSettings(unittest.TestCase):
    def test_postgres_defaults_and_validation(self):
        with patch.dict(
            os.environ,
            {
                "SUB2GEN_DB_SCHEMA": "sub2gen",
                "SUB2GEN_DB_POOL_MIN_SIZE": "2",
                "SUB2GEN_DB_POOL_MAX_SIZE": "10",
            },
            clear=False,
        ):
            settings = DatabaseSettings.from_env(
                backend="postgres", url="postgresql://user:password@localhost/sub2gen"
            )
        self.assertEqual(settings.backend, "postgres")
        self.assertEqual(settings.pool_min_size, 2)
        self.assertEqual(settings.pool_max_size, 10)

    def test_invalid_schema_is_rejected(self):
        with patch.dict(os.environ, {"SUB2GEN_DB_SCHEMA": "bad-schema"}, clear=False):
            with self.assertRaises(ValueError):
                DatabaseSettings.from_env(backend="postgres", url="postgresql://localhost/sub2gen")


class TestPostgresDialect(unittest.TestCase):
    def test_placeholders_dates_booleans_and_ignore_are_translated(self):
        query = translate_sql(
            """
            INSERT OR IGNORE INTO api_clients (name, is_active)
            VALUES (?, 1)
            """
        )
        self.assertIn("VALUES (%s, TRUE)", query)
        self.assertIn("ON CONFLICT DO NOTHING", query)
        self.assertNotIn("?", query)

        query = translate_sql("SELECT * FROM tokens WHERE is_active = 1 AND datetime(created_at) >= datetime('now', ?)")
        self.assertIn("is_active = TRUE", query)
        self.assertIn("created_at >= CURRENT_TIMESTAMP + (%s)::interval", query)
        self.assertNotIn("datetime(", query)

    def test_replace_and_scalar_max_are_translated(self):
        query = translate_sql(
            "INSERT OR REPLACE INTO api_key_rate_limits "
            "(api_key_id, endpoint, rpm, rph, burst, updated_at) "
            "VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)"
        )
        self.assertIn("ON CONFLICT (api_key_id, endpoint) DO UPDATE SET", query)
        self.assertNotIn("INSERT OR REPLACE", query)
        update = translate_sql(
            "UPDATE request_logs SET request_size_bytes = MAX(COALESCE(request_size_bytes, 0), ?) WHERE id = ?"
        )
        self.assertIn("GREATEST(COALESCE(request_size_bytes, 0), %s)", update)

    def test_boolean_parameters_are_context_aware(self):
        query = translate_sql("UPDATE api_keys SET is_active = ? WHERE id = ?")
        params = coerce_boolean_parameters(query, (1, 1))
        self.assertIs(params[0], True)
        self.assertEqual(params[1], 1)

    def test_initial_migration_is_checksummed_and_postgres_native(self):
        migrations = discover_migrations()
        self.assertEqual([migration.revision for migration in migrations], ["0001", "0002", "0003", "0004"])
        self.assertTrue(all(len(migration.checksum) == 64 for migration in migrations))
        sql_text = migrations[0].sql_text
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", sql_text)
        self.assertIn("TIMESTAMPTZ", sql_text)
        self.assertIn("CREATE TABLE system_metadata", sql_text)
        self.assertNotIn("AUTOINCREMENT", sql_text)
        self.assertNotIn("PRAGMA", sql_text)

        tables, indexes = baseline_schema_signature(migrations[0])
        self.assertIn("tokens", tables)
        self.assertIn("st", tables["tokens"])
        self.assertIn("system_metadata", tables)
        self.assertIn("idx_token_st", indexes)


class TestEncryptedPostgresBackup(unittest.TestCase):
    def test_streaming_aes_gcm_roundtrip_and_tamper_detection(self):
        key = os.urandom(32)
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "plain.tar.gz"
            encrypted = root / "backup.s2g"
            restored = root / "restored.tar.gz"
            source.write_bytes(os.urandom(2 * 1024 * 1024 + 37))
            metadata = encrypt_archive(source, encrypted, key_id="key-1", key=key)
            header, _prefix, _offset = encrypted_archive_header(encrypted)
            self.assertEqual(header["key_id"], "key-1")
            self.assertEqual(metadata["algorithm"], "AES-256-GCM")
            decrypt_archive(encrypted, restored, keys={"key-1": key})
            self.assertEqual(restored.read_bytes(), source.read_bytes())

            payload = bytearray(encrypted.read_bytes())
            payload[-20] ^= 1
            encrypted.write_bytes(payload)
            with self.assertRaises(PostgresBackupError):
                decrypt_archive(encrypted, restored, keys={"key-1": key})

    def test_key_ring_requires_32_byte_active_key(self):
        good_key = base64.b64encode(os.urandom(32)).decode("ascii")
        with patch.dict(
            os.environ,
            {
                "SUB2GEN_BACKUP_ACTIVE_KEY_ID": "current",
                "SUB2GEN_BACKUP_KEYS_JSON": '{"current":"' + good_key + '"}',
            },
            clear=False,
        ):
            active, keys = load_backup_keys()
        self.assertEqual(active, "current")
        self.assertEqual(len(keys[active]), 32)


class TestPostgresBackupSnapshot(unittest.IsolatedAsyncioTestCase):
    async def test_pg_dump_and_manifest_counts_share_an_exported_snapshot(self):
        key = os.urandom(32)
        encoded = base64.b64encode(key).decode("ascii")
        snapshot = SimpleNamespace(
            snapshot_id="00000003-0000002A-1",
            counts={"tokens": 3},
            close=AsyncMock(),
        )
        database = SimpleNamespace(
            database_url="postgresql://user:password@localhost/sub2gen",
            schema="sub2gen",
            health_snapshot=AsyncMock(
                return_value={
                    "database_revision": "0001",
                    "cutover_marker_present": True,
                }
            ),
        )

        async def fake_run(command, *, env):
            dump_path = Path(command[command.index("--file") + 1])
            dump_path.write_bytes(b"postgres-custom-dump")

        with (
            tempfile.TemporaryDirectory() as temporary,
            patch.dict(
                os.environ,
                {
                    "SUB2GEN_BACKUP_ACTIVE_KEY_ID": "current",
                    "SUB2GEN_BACKUP_KEYS_JSON": '{"current":"' + encoded + '"}',
                },
                clear=False,
            ),
            patch("sub2gen.services.postgres_backup._require_pg16", new=AsyncMock()),
            patch(
                "sub2gen.services.postgres_backup.open_backup_snapshot",
                new=AsyncMock(return_value=snapshot),
            ),
            patch(
                "sub2gen.services.postgres_backup._run_process",
                new=AsyncMock(side_effect=fake_run),
            ) as run_process,
        ):
            root = Path(temporary)
            profiles = root / "profiles"
            profiles.mkdir()
            encrypted = root / "backup.s2g"
            manifest = await create_postgres_archive(
                database,
                profiles,
                root / "work",
                encrypted,
                backup_id="backup-1",
                backup_type="manual",
                app_version="test",
            )

        command = run_process.await_args.args[0]
        self.assertEqual(command[command.index("--snapshot") + 1], snapshot.snapshot_id)
        self.assertEqual(manifest["row_counts"], {"tokens": 3})
        snapshot.close.assert_awaited_once()


if __name__ == "__main__":
    unittest.main()
