# Generated by scripts/generate.py from worker-protocol-v1.schema.json. Do not edit.
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

PROTOCOL_VERSION = "1.0"


class MessageType(StrEnum):
    WORKER_HELLO = "worker.hello"
    WORKER_CHALLENGE = "worker.challenge"
    WORKER_REGISTER = "worker.register"
    WORKER_REGISTERED = "worker.registered"
    WORKER_CAPABILITIES = "worker.capabilities"
    WORKER_HEARTBEAT = "worker.heartbeat"
    JOB_OFFER = "job.offer"
    JOB_ACCEPT = "job.accept"
    JOB_REJECT = "job.reject"
    JOB_PROGRESS = "job.progress"
    JOB_RESULT = "job.result"
    JOB_ERROR = "job.error"
    JOB_CANCEL = "job.cancel"
    JOB_CANCELLED = "job.cancelled"


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class WorkerPolicy(StrictModel):
    allowed_servers: tuple[str, ...] = ()
    allowed_capabilities: tuple[str, ...]
    allowed_models: tuple[str, ...] = ()
    allowed_accounts: tuple[str, ...] = ()
    max_concurrency: int = Field(default=1, ge=1)
    daily_job_limit: int | None = Field(default=None, ge=1)
    confirm_new_servers: bool = True


class WorkerHelloPayload(StrictModel):
    supported_versions: tuple[str, ...]
    worker_kind: str
    instance_id: str


class WorkerChallengePayload(StrictModel):
    challenge_id: str
    nonce: str
    expires_at: datetime


class WorkerRegisterPayload(StrictModel):
    selected_version: Literal["1.0"]
    challenge_id: str
    signature: str
    capabilities: tuple[str, ...]
    worker_session_id: str


class WorkerRegisteredPayload(StrictModel):
    selected_version: Literal["1.0"]
    worker_session_id: str
    lease_seconds: int = Field(ge=1)


class WorkerCapabilitiesPayload(StrictModel):
    capabilities: tuple[str, ...]


class WorkerHeartbeatPayload(StrictModel):
    worker_session_id: str
    active_leases: tuple[str, ...] = ()
    available_slots: int = Field(ge=0)


class JobOfferPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    capability: str
    deadline: datetime
    input: dict[str, Any]
    artifact_upload_grants: tuple[dict[str, Any], ...] = ()
    api_key_identity: str | None = None


class JobDecisionPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    reason: str | None = None


class JobProgressPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    progress: float | None = Field(default=None, ge=0, le=1)
    phase: str | None = None
    detail: dict[str, Any] = Field(default_factory=dict)


class JobResultPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    output: dict[str, Any]


class StructuredError(StrictModel):
    code: str
    message: str
    retryable: bool = False
    detail: dict[str, Any] = Field(default_factory=dict)


class JobErrorPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    error: StructuredError


class JobCancelPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    reason: str | None = None


class JobCancelledPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str


class Envelope(StrictModel):
    protocol_version: Literal["1.0"] = PROTOCOL_VERSION
    message_id: str
    message_type: MessageType
    correlation_id: str | None
    job_id: str | None
    job_kind: str | None
    worker_id: str
    sent_at: datetime
    payload: dict[str, Any]

    @field_validator("message_id", "worker_id")
    @classmethod
    def require_non_empty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("value must not be empty")
        return value

    @model_validator(mode="after")
    def validate_job_identity(self) -> "Envelope":
        if self.message_type.value.startswith("job.") and (not self.job_id or not self.job_kind):
            raise ValueError("job messages require job_id and job_kind")
        return self
