// Generated by scripts/generate.py from worker-protocol-v1.schema.json. Do not edit.
export const PROTOCOL_VERSION = "1.0" as const
export const MESSAGE_TYPES = ["worker.hello","worker.challenge","worker.register","worker.registered","worker.capabilities","worker.heartbeat","job.offer","job.accept","job.reject","job.progress","job.result","job.error","job.cancel","job.cancelled"] as const
export type MessageType = "worker.hello" | "worker.challenge" | "worker.register" | "worker.registered" | "worker.capabilities" | "worker.heartbeat" | "job.offer" | "job.accept" | "job.reject" | "job.progress" | "job.result" | "job.error" | "job.cancel" | "job.cancelled"

export interface WorkerPolicy {
  allowed_servers: readonly string[]
  allowed_capabilities: readonly string[]
  allowed_models: readonly string[]
  allowed_accounts: readonly string[]
  max_concurrency: number
  daily_job_limit: number | null
  confirm_new_servers: boolean
}

export interface Envelope<TPayload extends Record<string, unknown> = Record<string, unknown>> {
  protocol_version: typeof PROTOCOL_VERSION
  message_id: string
  message_type: MessageType
  correlation_id: string | null
  job_id: string | null
  job_kind: string | null
  worker_id: string
  sent_at: string
  payload: TPayload
}

export interface WorkerHelloPayload extends Record<string, unknown> {
  supported_versions: readonly string[]
  worker_kind: string
  instance_id: string
}

export interface WorkerChallengePayload extends Record<string, unknown> {
  challenge_id: string
  nonce: string
  expires_at: string
}

export interface WorkerRegisterPayload extends Record<string, unknown> {
  selected_version: typeof PROTOCOL_VERSION
  challenge_id: string
  signature: string
  capabilities: readonly string[]
  worker_session_id: string
}

export interface WorkerRegisteredPayload extends Record<string, unknown> {
  selected_version: typeof PROTOCOL_VERSION
  worker_session_id: string
  lease_seconds: number
}

export interface WorkerCapabilitiesPayload extends Record<string, unknown> {
  capabilities: readonly string[]
}

export interface WorkerHeartbeatPayload extends Record<string, unknown> {
  worker_session_id: string
  active_leases: readonly string[]
  available_slots: number
}

export interface JobOfferPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  capability: string
  deadline: string
  input: Record<string, unknown>
  artifact_upload_grants: readonly Record<string, unknown>[]
  api_key_identity?: string | null
}

export interface JobDecisionPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  reason?: string | null
}

export interface JobProgressPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  progress?: number | null
  phase?: string | null
  detail: Record<string, unknown>
}

export interface JobResultPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  output: Record<string, unknown>
}

export interface StructuredError {
  code: string
  message: string
  retryable: boolean
  detail: Record<string, unknown>
}

export interface JobErrorPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  error: StructuredError
}

export interface JobCancelPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
  reason?: string | null
}

export interface JobCancelledPayload extends Record<string, unknown> {
  attempt: number
  lease_id: string
}
