"""Generate Python and TypeScript worker protocol types from the canonical schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "worker-protocol-v1.schema.json"
PYTHON_PATH = ROOT / "src" / "sub2gen_worker_protocol" / "generated.py"
TYPESCRIPT_PATH = ROOT / "src" / "generated.ts"


def _python_source(message_types: list[str], protocol_version: str) -> str:
    enum_lines = "\n".join(
        f'    {value.upper().replace(".", "_")} = "{value}"' for value in message_types
    )
    return f'''# Generated by scripts/generate.py from worker-protocol-v1.schema.json. Do not edit.
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

PROTOCOL_VERSION = "{protocol_version}"


class MessageType(StrEnum):
{enum_lines}


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class WorkerPolicy(StrictModel):
    allowed_servers: tuple[str, ...] = ()
    allowed_capabilities: tuple[str, ...]
    allowed_models: tuple[str, ...] = ()
    allowed_accounts: tuple[str, ...] = ()
    max_concurrency: int = Field(default=1, ge=1)
    daily_job_limit: int | None = Field(default=None, ge=1)
    confirm_new_servers: bool = True


class WorkerHelloPayload(StrictModel):
    supported_versions: tuple[str, ...]
    worker_kind: str
    instance_id: str


class WorkerChallengePayload(StrictModel):
    challenge_id: str
    nonce: str
    expires_at: datetime


class WorkerRegisterPayload(StrictModel):
    selected_version: Literal["{protocol_version}"]
    challenge_id: str
    signature: str
    capabilities: tuple[str, ...]
    worker_session_id: str


class WorkerRegisteredPayload(StrictModel):
    selected_version: Literal["{protocol_version}"]
    worker_session_id: str
    lease_seconds: int = Field(ge=1)


class WorkerCapabilitiesPayload(StrictModel):
    capabilities: tuple[str, ...]


class WorkerHeartbeatPayload(StrictModel):
    worker_session_id: str
    active_leases: tuple[str, ...] = ()
    available_slots: int = Field(ge=0)


class JobOfferPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    capability: str
    deadline: datetime
    input: dict[str, Any]
    artifact_upload_grants: tuple[dict[str, Any], ...] = ()
    api_key_identity: str | None = None


class JobDecisionPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    reason: str | None = None


class JobProgressPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    progress: float | None = Field(default=None, ge=0, le=1)
    phase: str | None = None
    detail: dict[str, Any] = Field(default_factory=dict)


class JobResultPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    output: dict[str, Any]


class StructuredError(StrictModel):
    code: str
    message: str
    retryable: bool = False
    detail: dict[str, Any] = Field(default_factory=dict)


class JobErrorPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    error: StructuredError


class JobCancelPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str
    reason: str | None = None


class JobCancelledPayload(StrictModel):
    attempt: int = Field(ge=1)
    lease_id: str


class Envelope(StrictModel):
    protocol_version: Literal["{protocol_version}"] = PROTOCOL_VERSION
    message_id: str
    message_type: MessageType
    correlation_id: str | None
    job_id: str | None
    job_kind: str | None
    worker_id: str
    sent_at: datetime
    payload: dict[str, Any]

    @field_validator("message_id", "worker_id")
    @classmethod
    def require_non_empty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("value must not be empty")
        return value

    @model_validator(mode="after")
    def validate_job_identity(self) -> "Envelope":
        if self.message_type.value.startswith("job.") and (not self.job_id or not self.job_kind):
            raise ValueError("job messages require job_id and job_kind")
        return self
'''


def _typescript_source(message_types: list[str], protocol_version: str) -> str:
    union = " | ".join(json.dumps(item) for item in message_types)
    values = json.dumps(message_types, separators=(",", ":"))
    return f'''// Generated by scripts/generate.py from worker-protocol-v1.schema.json. Do not edit.
export const PROTOCOL_VERSION = "{protocol_version}" as const
export const MESSAGE_TYPES = {values} as const
export type MessageType = {union}

export interface WorkerPolicy {{
  allowed_servers: readonly string[]
  allowed_capabilities: readonly string[]
  allowed_models: readonly string[]
  allowed_accounts: readonly string[]
  max_concurrency: number
  daily_job_limit: number | null
  confirm_new_servers: boolean
}}

export interface Envelope<TPayload extends Record<string, unknown> = Record<string, unknown>> {{
  protocol_version: typeof PROTOCOL_VERSION
  message_id: string
  message_type: MessageType
  correlation_id: string | null
  job_id: string | null
  job_kind: string | null
  worker_id: string
  sent_at: string
  payload: TPayload
}}

export interface WorkerHelloPayload extends Record<string, unknown> {{
  supported_versions: readonly string[]
  worker_kind: string
  instance_id: string
}}

export interface WorkerChallengePayload extends Record<string, unknown> {{
  challenge_id: string
  nonce: string
  expires_at: string
}}

export interface WorkerRegisterPayload extends Record<string, unknown> {{
  selected_version: typeof PROTOCOL_VERSION
  challenge_id: string
  signature: string
  capabilities: readonly string[]
  worker_session_id: string
}}

export interface WorkerRegisteredPayload extends Record<string, unknown> {{
  selected_version: typeof PROTOCOL_VERSION
  worker_session_id: string
  lease_seconds: number
}}

export interface WorkerCapabilitiesPayload extends Record<string, unknown> {{
  capabilities: readonly string[]
}}

export interface WorkerHeartbeatPayload extends Record<string, unknown> {{
  worker_session_id: string
  active_leases: readonly string[]
  available_slots: number
}}

export interface JobOfferPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  capability: string
  deadline: string
  input: Record<string, unknown>
  artifact_upload_grants: readonly Record<string, unknown>[]
  api_key_identity?: string | null
}}

export interface JobDecisionPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  reason?: string | null
}}

export interface JobProgressPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  progress?: number | null
  phase?: string | null
  detail: Record<string, unknown>
}}

export interface JobResultPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  output: Record<string, unknown>
}}

export interface StructuredError {{
  code: string
  message: string
  retryable: boolean
  detail: Record<string, unknown>
}}

export interface JobErrorPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  error: StructuredError
}}

export interface JobCancelPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
  reason?: string | null
}}

export interface JobCancelledPayload extends Record<string, unknown> {{
  attempt: number
  lease_id: string
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = schema["properties"]["protocol_version"]["const"]
    message_types = schema["$defs"]["messageType"]["enum"]
    outputs = {
        PYTHON_PATH: _python_source(message_types, version),
        TYPESCRIPT_PATH: _typescript_source(message_types, version),
    }
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            raise SystemExit("Generated worker protocol files are stale: " + ", ".join(map(str, stale)))
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
